/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package r1_175480;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import ws3dproxy.CommandExecException;
import ws3dproxy.model.Bag;
import ws3dproxy.model.Creature;
import ws3dproxy.model.Leaflet;
import ws3dproxy.model.Thing;
import ws3dproxy.model.World;

/**
 *
 * @author patrickctrf
 */
public class GuiControles extends javax.swing.JFrame {

    public World w;
    public Creature c;
    private JTextField textField;   // texField que funciona delistener do teclado

    private double coordX;      //coordenada X selecionada na interface
    private double coordY;      //coordenada Y selecionada na interface
    private int itemjListCores; //item selecionado na lista de cores
    private int itemjListTipoDeComida;  //item selecionado na lista de comidas.

    /**
     * Creates new form gui_controles
     */
    public GuiControles(World w, Creature c, JTextField textField) {
        this.coordX = 0;
        this.coordY = 0;
        this.itemjListTipoDeComida = 0;
        this.itemjListCores = 0;
        this.w = w;
        this.c = c;
        this.textField = textField;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonCriarComida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTipoDeComida = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCores = new javax.swing.JList<>();
        jButtonCriarJoia = new javax.swing.JButton();
        jTextX = new javax.swing.JTextField();
        jTextY = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonComeOuGuarda = new javax.swing.JButton();
        jButtonEntregarLeaflet = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLeaflet = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableBag = new javax.swing.JTable();
        fuelTitle = new javax.swing.JTextField();
        fuelValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCriarComida.setText("Criar Comida");
        jButtonCriarComida.setFocusable(false);
        jButtonCriarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarComidaActionPerformed(evt);
            }
        });

        jListTipoDeComida.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Perecivel", "Nao-Perecivel" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListTipoDeComida.setFocusable(false);
        jListTipoDeComida.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTipoDeComidaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListTipoDeComida);

        jListCores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Red", "Green", "Blue", "Yellow", "Magenta", "White" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListCores.setFocusable(false);
        jListCores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCoresValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListCores);

        jButtonCriarJoia.setText("Criar Joia");
        jButtonCriarJoia.setFocusable(false);
        jButtonCriarJoia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarJoiaActionPerformed(evt);
            }
        });

        jTextX.setText("0.0");
        jTextX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextXActionPerformed(evt);
            }
        });

        jTextY.setText("0.0");
        jTextY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextYActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(" Coordenada X");
        jTextArea1.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Coordenada Y");
        jTextArea2.setFocusable(false);
        jScrollPane4.setViewportView(jTextArea2);

        jButtonComeOuGuarda.setText("Comer ou Guardar");
        jButtonComeOuGuarda.setFocusable(false);
        jButtonComeOuGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComeOuGuardaActionPerformed(evt);
            }
        });

        jButtonEntregarLeaflet.setText("Entrega Leaflet");
        jButtonEntregarLeaflet.setFocusable(false);
        jButtonEntregarLeaflet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntregarLeafletActionPerformed(evt);
            }
        });

        jTableLeaflet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Red", null, null, null, null},
                {"Green", null, null, null, null},
                {"Blue", null, null, null, null},
                {"Yellow", null, null, null, null},
                {"Magenta", null, null, null, null},
                {"White", null, null, null, null},
                {"Completed", null, null, null, null},
                {"Value", null, null, null, null}
            },
            new String [] {
                "", "LF 1", "LF 2", "LF 3", "Coletadas"
            }
        ));
        jScrollPane5.setViewportView(jTableLeaflet);
        if (jTableLeaflet.getColumnModel().getColumnCount() > 0) {
            jTableLeaflet.getColumnModel().getColumn(1).setResizable(false);
        }

        jTableBag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"totalFood", null},
                {"totalJewels", null}
            },
            new String [] {
                "BAG", "Qtde Jóias"
            }
        ));
        jScrollPane6.setViewportView(jTableBag);

        fuelTitle.setText("Fuel: ");
        fuelTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTitleActionPerformed(evt);
            }
        });

        fuelValue.setText("1000.0000");
        fuelValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButtonCriarComida)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCriarJoia)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonComeOuGuarda)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEntregarLeaflet)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(fuelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fuelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCriarJoia)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCriarComida)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButtonComeOuGuarda)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonEntregarLeaflet)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fuelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fuelValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Metodo chamado quando o usuario clica no botao "Criar Comida"
    private void jButtonCriarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarComidaActionPerformed
        try {
            // TODO add your handling code here:
            World.createFood(this.itemjListTipoDeComida, this.coordX, this.coordY);
        } catch (CommandExecException ex) {
            System.out.println("Excecao na criacao da comida");
        }
    }//GEN-LAST:event_jButtonCriarComidaActionPerformed

    // Metodo chamado quando um novo item eh selecionado na lista de comida.
    private void jListTipoDeComidaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTipoDeComidaValueChanged
        // TODO add your handling code here:
        this.itemjListTipoDeComida = this.jListTipoDeComida.getSelectedIndex();
    }//GEN-LAST:event_jListTipoDeComidaValueChanged

    // Metodo para criacao de Joia quando o botao eh pressionado.
    private void jButtonCriarJoiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarJoiaActionPerformed
        try {
            // TODO add your handling code here:
            World.createJewel(this.itemjListCores, this.coordX, this.coordY);
        } catch (CommandExecException ex) {
            System.out.println("Excecao na criacao da Joia");
        }
    }//GEN-LAST:event_jButtonCriarJoiaActionPerformed

    //Metodo que recebe o evento de no item selecionado na lista de cores
    private void jListCoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCoresValueChanged
        // TODO add your handling code here:
        this.itemjListCores = this.jListCores.getSelectedIndex();
    }//GEN-LAST:event_jListCoresValueChanged

    //Chamada de evento para nova coordenada X setada.
    private void jTextXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextXActionPerformed
        // TODO add your handling code here:
        this.coordX = Double.parseDouble(this.jTextX.getText());
        this.textField.requestFocus();
    }//GEN-LAST:event_jTextXActionPerformed

    //Chamada de evento para nova coordenada Y setada.
    private void jTextYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextYActionPerformed
        // TODO add your handling code here:
        this.coordY = Double.parseDouble(this.jTextY.getText());
        this.textField.requestFocus();
    }//GEN-LAST:event_jTextYActionPerformed

    protected void updateLeafletTable() {
        c.updateState();
        List<Leaflet> leaflets = c.getLeaflets();
        String[] cores = {"Red", "Green", "Blue", "Yellow", "Magenta", "White"};
        int[] totalJoias = {0, 0, 0, 0, 0, 0,};
        Bag bag = c.updateBag();
        c.updateState();

        // i comeca em 1 pq pulamos a coluna de titulos.
        int i = 1, j = 0;
        for (Leaflet leaflet : leaflets) {
            j = 0;
            for (String cor : cores) {
                jTableLeaflet.setValueAt(
                        leaflet.getItems().getOrDefault(
                                cor,
                                new Integer[]{0, 0})[0],
                        j, i);
                totalJoias[j] = totalJoias[j] + leaflet.getItems().getOrDefault(cor, new Integer[]{0, 0})[1];
                j++;
            }
            jTableLeaflet.setValueAt(leaflet.getSituation() == 1 ? "Yes" : "No", j, i);
            j++;
            jTableLeaflet.setValueAt(leaflet.getPayment(), j, i);
            j++;
            i++;
        }

        j = 0;
        for (String cor : cores) {
            jTableLeaflet.setValueAt(bag.getNumberCrystalPerType(cor),
                    j, i);
            j++;
        }
        c.updateState();
    }

    protected void updateBagTable() {
        c.updateState();
        String[] cores = {"Red", "Green", "Blue", "Yellow", "Magenta", "White"};

        Bag bag = c.updateBag();

        jTableBag.setValueAt(bag.getTotalNumberFood(), 0, 1);
        jTableBag.setValueAt(bag.getTotalNumberCrystals(), 1, 1);
        c.updateState();
    }

    private void jButtonEntregarLeafletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntregarLeafletActionPerformed
        c.updateState();
        updateLeafletTable();
        updateBagTable();
        c.updateState();
        updateLeafletTable();
        updateBagTable();
        try {
            // TODO add your handling code here:
            Leaflet leafletExtraido = c.getLeaflets().get(0);
            c.deliverLeaflet("" + leafletExtraido.getID());
        } catch (CommandExecException ex) {
            System.out.println("Nao foi possivel entregar LeafLet");
        }
        c.updateState();
        updateLeafletTable();
        updateBagTable();
        c.updateState();
        updateLeafletTable();
        updateBagTable();
    }//GEN-LAST:event_jButtonEntregarLeafletActionPerformed

    private void jButtonComeOuGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComeOuGuardaActionPerformed
        // TODO add your handling code here:
        c.updateState();
        updateLeafletTable();
        updateBagTable();
        c.updateState();
        List<Thing> thingsInVisionList = c.getThingsInVision();
        String thingsNames = c.getThingsNames();

        if (!thingsInVisionList.isEmpty()) {
            try {
                this.c.eatIt(thingsInVisionList.get(0).getName());
                System.out.println("Objeto foi comido.");
            } catch (CommandExecException ex) {
                System.out.println("Não foi possivel comer o objeto.");
            }

            try {
                this.c.putInSack(thingsInVisionList.get(0).getName());
                System.out.println("Objeto guardado na sacola.");
            } catch (CommandExecException ex) {
                System.out.println("Nao foi possivel colocar na sacola.");
            }
        }
        c.updateState();
        updateLeafletTable();
        updateBagTable();
        c.updateState();
        updateLeafletTable();
        updateBagTable();
    }//GEN-LAST:event_jButtonComeOuGuardaActionPerformed

    private void fuelTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTitleActionPerformed

    private void fuelValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelValueActionPerformed

    public void atualizaFuel(){
        c.updateState();
        updateLeafletTable();
        updateBagTable();
        
        fuelValue.setText("" + c.getFuel()/10);
        
        c.updateState();
        updateLeafletTable();
        updateBagTable();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fuelTitle;
    private javax.swing.JTextField fuelValue;
    private javax.swing.JButton jButtonComeOuGuarda;
    private javax.swing.JButton jButtonCriarComida;
    private javax.swing.JButton jButtonCriarJoia;
    private javax.swing.JButton jButtonEntregarLeaflet;
    private javax.swing.JList<String> jListCores;
    private javax.swing.JList<String> jListTipoDeComida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableBag;
    private javax.swing.JTable jTableLeaflet;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextX;
    private javax.swing.JTextField jTextY;
    // End of variables declaration//GEN-END:variables

    public int getItemjListCores() {
        return itemjListCores;
    }

    public int getItemjListTipoDeComida() {
        return itemjListTipoDeComida;
    }
}
